//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using QuanLyTiecCuoi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUDATBAN:BaseViewModel
    {
        private int _MaPhieuDatBan;
        private int _MaMonAn;
        private int _SoLuong;
        private decimal _ThanhTien;
        public int MaPhieuDatBan { get => _MaPhieuDatBan; set { _MaPhieuDatBan = value; OnPropertyChanged(); }}
        public int MaMonAn { get => _MaMonAn; set { _MaMonAn = value; OnPropertyChanged(); } }
        public int SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }
        public decimal ThanhTien { get => _ThanhTien; set { _ThanhTien = value; OnPropertyChanged(); } }

        public virtual MONAN MONAN { get; set; }
        public virtual PHIEUDATBAN PHIEUDATBAN { get; set; }
    }
}
