//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using QuanLyTiecCuoi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.PHIEUDATDICHVUs = new HashSet<PHIEUDATDICHVU>();
        }
    
        public int MaDichVu { get => _MaDichVu; set { _MaDichVu = value; OnPropertyChanged(); } }
        public string TenDichVu { get => _TenDichVu; set { _TenDichVu = value; OnPropertyChanged(); } }
        public decimal DonGia { get => _DonGia; set { _DonGia = value; OnPropertyChanged(); } }
        public string MoTa { get => _MoTa; set { _MoTa = value; OnPropertyChanged(); } }
        public string HinhAnh { get => _HinhAnh; set { _HinhAnh = value; OnPropertyChanged(); } }
        public string GhiChu { get => _GhiChu; set { _GhiChu = value; OnPropertyChanged(); } }

        private int _MaDichVu;
        private string _TenDichVu;
        private decimal _DonGia;
        private string _MoTa;
        private string _HinhAnh;
        private string _GhiChu;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATDICHVU> PHIEUDATDICHVUs { get; set; }
    }
}
