//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using QuanLyTiecCuoi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONAN()
        {
            this.CT_PHIEUDATBAN = new HashSet<CT_PHIEUDATBAN>();
        }
    
        private int _MaMonAn { get; set; }
        public int MaMonAn { get => _MaMonAn; set { _MaMonAn = value;OnPropertyChanged(); } }
        private string _TenMonAn { get; set; }
        public string TenMonAn { get => _TenMonAn; set { _TenMonAn = value; OnPropertyChanged(); } }
        private decimal _DonGia { get; set; }
        public decimal DonGia { get => _DonGia; set { _DonGia = value; OnPropertyChanged(); } }
        private string _MoTa { get; set; }
        public string MoTa { get => _MoTa; set { _MoTa = value;OnPropertyChanged(); } }
        public string HinhAnh { get; set; }
        private string _GhiChu { get; set; }
        public string GhiChu { get => _GhiChu; set { _GhiChu = value;OnPropertyChanged(); } }
        private int _MaLoaiMonAn { get; set; }
        public int MaLoaiMonAn { get => _MaLoaiMonAn; set { _MaLoaiMonAn = value;OnPropertyChanged(); } }
    
        public virtual LOAIMONAN LOAIMONAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDATBAN> CT_PHIEUDATBAN { get; set; }
    }
}
