//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATBAN
    {
        public string MaPhieuDatBan { get; set; }
        public string MaTiecCuoi { get; set; }
        public string MaLoaiBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SoLuongDuTru { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LOAIBAN LOAIBAN { get; set; }
        public virtual TIECCUOI TIECCUOI { get; set; }
    }
}
