//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiecCuoi.Model
{
    using QuanLyTiecCuoi.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDATDICHVU: BaseViewModel
    {
        private int _MaTiecCuoi;
        private int _MaDichVu;
        private int _SoLuong = 0;
        private decimal _ThanhTien = 0;
        private string _GhiChu;
        public int MaTiecCuoi { get => _MaTiecCuoi; set { _MaTiecCuoi = value; OnPropertyChanged(); } }
        public int MaDichVu { get => _MaDichVu; set { _MaDichVu = value; OnPropertyChanged(); } }
        public int SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }
        public decimal ThanhTien { get => _ThanhTien; set { _ThanhTien = value; OnPropertyChanged(); } }
        public string GhiChu { get => _GhiChu; set { _GhiChu = value; OnPropertyChanged(); } }

        public virtual DICHVU DICHVU { get; set; }
        public virtual TIECCUOI TIECCUOI { get; set; }
    }
}
