USE [master]
GO
/****** Object:  Database [QuanLyTiecCuoi]    Script Date: 6/13/2020 3:30:34 PM ******/
CREATE DATABASE [QuanLyTiecCuoi]
GO
USE [QuanLyTiecCuoi]
GO
/****** Object:  Table [dbo].[BAOCAONGAY]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAOCAONGAY](
	[MaBaoCaoThang] [int] NOT NULL,
	[Ngay] [int] NOT NULL,
	[SoLuongTiecCuoi] [int] NOT NULL,
	[DoanhThu] [money] NOT NULL,
	[TiLe] [float] NOT NULL,
 CONSTRAINT [PK_BCN] PRIMARY KEY CLUSTERED 
(
	[MaBaoCaoThang] ASC,
	[Ngay] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BAOCAOTHANG]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BAOCAOTHANG](
	[MaBaoCaoThang] [int] IDENTITY(1,1) NOT NULL,
	[Thang] [int] NOT NULL,
	[Nam] [int] NOT NULL,
	[TongDoanhThu] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaBaoCaoThang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CA]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CA](
	[MaCa] [int] IDENTITY(1,1) NOT NULL,
	[TenCa] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHUCNANG]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHUCNANG](
	[MaChucNang] [int] IDENTITY(1,1) NOT NULL,
	[TenChucNang] [nvarchar](max) NOT NULL,
	[TenManHinhDuocLoad] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaChucNang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CT_PHIEUDATBAN]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CT_PHIEUDATBAN](
	[MaPhieuDatBan] [int] NOT NULL,
	[MaMonAn] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonGia] [money] NOT NULL,
	[GhiChu] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DICHVU]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICHVU](
	[MaDichVu] [int] IDENTITY(1,1) NOT NULL,
	[TenDichVu] [nvarchar](max) NOT NULL,
	[DonGia] [money] NOT NULL,
	[MoTa] [nvarchar](max) NOT NULL,
	[HinhAnh] [varchar](max) NULL,
	[GhiChu] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDichVu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[MaHoaDon] [int] IDENTITY(1,1) NOT NULL,
	[TongTienBan] [money] NOT NULL,
	[TongTienDichVu] [money] NOT NULL,
	[TongTienHoaDon] [money] NOT NULL,
	[ConLai] [money] NOT NULL,
	[NgayThanhToan] [smalldatetime] NOT NULL,
	[MaTiecCuoi] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaHoaDon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIMONAN]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIMONAN](
	[MaLoaiMonAn] [int] IDENTITY(1,1) NOT NULL,
	[TenLoaiMonAn] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaLoaiMonAn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAISANH]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAISANH](
	[MaLoaiSanh] [int] IDENTITY(1,1) NOT NULL,
	[TenLoaiSanh] [nvarchar](max) NOT NULL,
	[DonGiaBanToiThieu] [money] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaLoaiSanh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MONAN]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MONAN](
	[MaMonAn] [int] IDENTITY(1,1) NOT NULL,
	[TenMonAn] [nvarchar](max) NOT NULL,
	[DonGia] [money] NOT NULL,
	[MoTa] [nvarchar](max) NOT NULL,
	[HinhAnh] [varchar](max) NULL,
	[GhiChu] [nvarchar](max) NULL,
	[MaLoaiMonAn] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaMonAn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NGUOIDUNG]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NGUOIDUNG](
	[Username] [varchar](20) NOT NULL,
	[Password] [varchar](20) NOT NULL,
	[TenNguoiDung] [nvarchar](max) NOT NULL,
	[MaNhomNguoiDung] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHOMNGUOIDUNG]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHOMNGUOIDUNG](
	[MaNhomNguoiDung] [int] IDENTITY(1,1) NOT NULL,
	[TenNhomNguoiDung] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNhomNguoiDung] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHANQUYEN]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHANQUYEN](
	[MaChucNang] [int] NOT NULL,
	[MaNhomNguoiDung] [int] NOT NULL,
 CONSTRAINT [PK_PQ] PRIMARY KEY CLUSTERED 
(
	[MaChucNang] ASC,
	[MaNhomNguoiDung] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUDATBAN]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUDATBAN](
	[MaPhieuDatBan] [int] IDENTITY(1,1) NOT NULL,
	[MaTiecCuoi] [int] NOT NULL,
	[LoaiBan] [nvarchar](max) NOT NULL,
	[SoLuong] [int] NOT NULL,
	[SoLuongDuTru] [int] NOT NULL,
	[DonGiaBan] [money] NOT NULL,
	[GhiChu] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaPhieuDatBan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUDATDICHVU]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUDATDICHVU](
	[MaTiecCuoi] [int] NOT NULL,
	[MaDichVu] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonGia] [money] NOT NULL,
 CONSTRAINT [PK_PDDV] PRIMARY KEY CLUSTERED 
(
	[MaTiecCuoi] ASC,
	[MaDichVu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SANH]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANH](
	[MaSanh] [int] IDENTITY(1,1) NOT NULL,
	[TenSanh] [nvarchar](max) NOT NULL,
	[SoLuongBanToiDa] [int] NOT NULL,
	[GhiChu] [nvarchar](max) NULL,
	[MaLoaiSanh] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSanh] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[THAMSO]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[THAMSO](
	[TenThamSo] [varchar](100) NOT NULL,
	[GiaTri] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TenThamSo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIECCUOI]    Script Date: 6/13/2020 3:30:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIECCUOI](
	[MaTiecCuoi] [int] IDENTITY(1,1) NOT NULL,
	[TenChuRe] [nvarchar](max) NOT NULL,
	[TenCoDau] [nvarchar](max) NOT NULL,
	[SoDienThoai] [varchar](20) NOT NULL,
	[NgayDatTiec] [smalldatetime] NOT NULL,
	[NgayDaiTiec] [smalldatetime] NOT NULL,
	[TienDatCoc] [money] NOT NULL,
	[GhiChu] [nvarchar](max) NULL,
	[MaSanh] [int] NOT NULL,
	[MaCa] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaTiecCuoi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CA] ON 

INSERT [dbo].[CA] ([MaCa], [TenCa]) VALUES (1, N'Trua')
INSERT [dbo].[CA] ([MaCa], [TenCa]) VALUES (2, N'Toi')
SET IDENTITY_INSERT [dbo].[CA] OFF
SET IDENTITY_INSERT [dbo].[LOAISANH] ON 

INSERT [dbo].[LOAISANH] ([MaLoaiSanh], [TenLoaiSanh], [DonGiaBanToiThieu]) VALUES (1, N'A', 1000000.0000)
INSERT [dbo].[LOAISANH] ([MaLoaiSanh], [TenLoaiSanh], [DonGiaBanToiThieu]) VALUES (2, N'B', 1100000.0000)
INSERT [dbo].[LOAISANH] ([MaLoaiSanh], [TenLoaiSanh], [DonGiaBanToiThieu]) VALUES (3, N'C', 1200000.0000)
INSERT [dbo].[LOAISANH] ([MaLoaiSanh], [TenLoaiSanh], [DonGiaBanToiThieu]) VALUES (4, N'D', 1400000.0000)
INSERT [dbo].[LOAISANH] ([MaLoaiSanh], [TenLoaiSanh], [DonGiaBanToiThieu]) VALUES (5, N'E', 1600000.0000)
SET IDENTITY_INSERT [dbo].[LOAISANH] OFF
INSERT [dbo].[THAMSO] ([TenThamSo], [GiaTri]) VALUES (N'ApDungQuiDinhPhat', 1)
INSERT [dbo].[THAMSO] ([TenThamSo], [GiaTri]) VALUES (N'TiLePhat', 0.01)
ALTER TABLE [dbo].[BAOCAONGAY]  WITH CHECK ADD FOREIGN KEY([MaBaoCaoThang])
REFERENCES [dbo].[BAOCAOTHANG] ([MaBaoCaoThang])
GO
ALTER TABLE [dbo].[CT_PHIEUDATBAN]  WITH CHECK ADD FOREIGN KEY([MaMonAn])
REFERENCES [dbo].[MONAN] ([MaMonAn])
GO
ALTER TABLE [dbo].[CT_PHIEUDATBAN]  WITH CHECK ADD FOREIGN KEY([MaPhieuDatBan])
REFERENCES [dbo].[PHIEUDATBAN] ([MaPhieuDatBan])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MaTiecCuoi])
REFERENCES [dbo].[TIECCUOI] ([MaTiecCuoi])
GO
ALTER TABLE [dbo].[MONAN]  WITH CHECK ADD FOREIGN KEY([MaLoaiMonAn])
REFERENCES [dbo].[LOAIMONAN] ([MaLoaiMonAn])
GO
ALTER TABLE [dbo].[NGUOIDUNG]  WITH CHECK ADD FOREIGN KEY([MaNhomNguoiDung])
REFERENCES [dbo].[NHOMNGUOIDUNG] ([MaNhomNguoiDung])
GO
ALTER TABLE [dbo].[PHANQUYEN]  WITH CHECK ADD FOREIGN KEY([MaChucNang])
REFERENCES [dbo].[CHUCNANG] ([MaChucNang])
GO
ALTER TABLE [dbo].[PHANQUYEN]  WITH CHECK ADD FOREIGN KEY([MaNhomNguoiDung])
REFERENCES [dbo].[NHOMNGUOIDUNG] ([MaNhomNguoiDung])
GO
ALTER TABLE [dbo].[PHIEUDATBAN]  WITH CHECK ADD FOREIGN KEY([MaTiecCuoi])
REFERENCES [dbo].[TIECCUOI] ([MaTiecCuoi])
GO
ALTER TABLE [dbo].[PHIEUDATDICHVU]  WITH CHECK ADD FOREIGN KEY([MaDichVu])
REFERENCES [dbo].[DICHVU] ([MaDichVu])
GO
ALTER TABLE [dbo].[PHIEUDATDICHVU]  WITH CHECK ADD FOREIGN KEY([MaTiecCuoi])
REFERENCES [dbo].[TIECCUOI] ([MaTiecCuoi])
GO
ALTER TABLE [dbo].[SANH]  WITH CHECK ADD FOREIGN KEY([MaLoaiSanh])
REFERENCES [dbo].[LOAISANH] ([MaLoaiSanh])
GO
ALTER TABLE [dbo].[TIECCUOI]  WITH CHECK ADD FOREIGN KEY([MaCa])
REFERENCES [dbo].[CA] ([MaCa])
GO
ALTER TABLE [dbo].[TIECCUOI]  WITH CHECK ADD FOREIGN KEY([MaSanh])
REFERENCES [dbo].[SANH] ([MaSanh])
GO
USE [master]
GO
ALTER DATABASE [QuanLyTiecCuoi] SET  READ_WRITE 
GO
